#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

cd "$repo_root"

./bin/shipguard self-audit --help >/dev/null
SHIPGUARD_GENERATED_AT="2026-06-16T00:00:00Z" \
  ./bin/shipguard self-audit --out "$tmp_dir/audit" >/dev/null

test -f "$tmp_dir/audit/self-audit.md"
test -f "$tmp_dir/audit/self-audit.json"
grep -q '"status": "pass"' "$tmp_dir/audit/self-audit.json"
grep -q '"commands_checked": 66' "$tmp_dir/audit/self-audit.json"
grep -q '"artifacts_checked": 194' "$tmp_dir/audit/self-audit.json"
grep -q '| shipguard ci-gate --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard arena import --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard arena compare --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard arena sign --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard arena verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ci-summary --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard check-run --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard check-run post --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard sarif --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard docs-check --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard value-gauntlet --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard web audit --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard web plan --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard backend audit --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard backend plan --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard cli audit --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard cli plan --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard score examples/scored-run.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios doctor --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios inventory --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios preview --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios devspace --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios devspace-check --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios brand --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard brand --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios target-match --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios codex-handoff --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios plan --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios prove --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios launchdeck --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios performance --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios design --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios modernize --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios app-intelligence --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios ai-readiness --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios external-audit --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios spec-workflow --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios report-quality --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios redact --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios eval --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios demo --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ios goals --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard codex status --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| README.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| NEXT_GOAL.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| LICENSE | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| CODE_OF_CONDUCT.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| CONTRIBUTING.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| GOVERNANCE.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| SECURITY.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| SUPPORT.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| .github/ISSUE_TEMPLATE/config.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| .github/ISSUE_TEMPLATE/workflow-gap.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| .github/ISSUE_TEMPLATE/bug-report.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| .github/ISSUE_TEMPLATE/proposal.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| .agents/plugins/marketplace.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| plugins/ios-shipguard/.codex-plugin/plugin.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| plugins/ios-shipguard/.mcp.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| plugins/ios-shipguard/skills/ios-shipguard/SKILL.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| plugins/ios-shipguard/skills/ios-shipguard/agents/openai.yaml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| plugins/ios-shipguard/skills/ios-shipguard/references/modes.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard transcript redact --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard transcript verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard transcript corpus --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-attest build --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-proof build --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-index build --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-manifest --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-manifest verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-replay verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-consume verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-diff compare --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-evidence site --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-evidence index --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-evidence bundle --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-evidence verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-evidence negative-index --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard next-goal --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/demo-reports/leaderboard.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/demo-reports/transcripts/corpus.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/demo-reports/transcripts/index.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/arena-compare/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-consume/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-diff/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-evidence/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-evidence-negative-index/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-evidence-verify/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-proof/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/transcript-corpus/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/transcript-verify/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/next-goal.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/arena-compare-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/sarif.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/docs-check.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/ci-summary.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/check-run.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/codex-status.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/compatibility.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/shipguard-naming.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/ios-preview.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/ios-shipguard.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/shipguard-devspace.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/template-profiles.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/transcript-corpus-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/transcript-corpus.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/transcript-redaction.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/transcript-verify-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-attest.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-consume-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-consume.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-diff-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-diff.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-bundle.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-index.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-negative-index-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-site.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-verify.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-proof.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-proof-consumption.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-manifest.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-index.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-proof-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-proof-workflows.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-replay.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/oss-evaluation.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/open-source.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/product-strategy.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/security-threat-model.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-proof-on-tag.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/arena-compare.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/transcript-corpus.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/transcript-verify.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-proof-manual.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-consume-verify.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-diff-compare.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-evidence-bundle.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-evidence-consume.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-evidence-export.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-evidence-negative-index.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/release-proof-consumption-checklist.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/redacted-transcript.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/transcripts/ios-notification-triage/transcript.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/transcripts/release-evidence-consumption/transcript.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| templates/web/AGENTS.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| templates/backend/AGENTS.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| templates/cli/AGENTS.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/external-arena-pack/imported-clean/run.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/arena/generated-artifact-cleanup-bypass/run.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/arena/github-posting-without-dry-run/run.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/arena/release-asset-trust-bypass/run.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/arena/security-token-leakage/run.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/arena/data-migration-loss-regression/run.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/arena/storekit-entitlement-regression/run.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/ios-devspace/complete-preview/handoff.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/ios-devspace/complete-preview/handoff.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/release-evidence/negative/README.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/release-evidence/negative/cases.tsv | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/tool-value-gauntlet/adoption-receipts/fresh-package-first-audit/receipt.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/tool-value-gauntlet/target-onboarding-receipts/fresh-ios-target-first-plan/receipt.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/tool-value-gauntlet/multi-profile-onboarding-receipts/all-starter-profiles-init-doctor/receipt.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/tool-value-gauntlet/profile-native-first-audit-receipts/web-backend-cli-first-audits/receipt.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/demo-ios-repo/DemoShipGuardApp.xcodeproj/project.pbxproj | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/demo-ios-repo/DemoProducts.storekit | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/demo-ios-repo/Sources/DemoShipGuardApp/DemoPermissions.swift | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/arena_sign.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/arena_compare.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/arena_verify.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_attest.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_consume.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_diff.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_evidence.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_proof.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_index.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_manifest.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_replay.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/codex_status.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_doctor.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_inventory.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_branding.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/profile_audit.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/profile_fix_plan.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/tool_value_gauntlet.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_launchdeck.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_performance.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_devspace_check.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_design.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_report_quality.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_scan_scope.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_shipguard_demo.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/shipguard_devspace_mcp.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/transcript_redact.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/transcript_verify.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/transcript_corpus.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/ios_branding_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/profile_audit_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/profile_fix_plan_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/profile_validation_receipts_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/command_family_runtime_output_receipts_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/tool_value_gauntlet_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/tool-value-gauntlet/profile-native-fix-plan-receipts/web-backend-cli-fix-plans/receipt.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/tool-value-gauntlet/profile-native-validation-receipts/web-backend-cli-validation-receipts/receipt.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/tool-value-gauntlet/command-family-runtime-output-receipts/major-family-report-outputs/receipt.json | pass |' "$tmp_dir/audit/self-audit.md"

echo "self audit tests passed"
