#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

cd "$repo_root"

./bin/codex-maintainer self-audit --help >/dev/null
CODEX_MAINTAINER_GENERATED_AT="2026-06-16T00:00:00Z" \
  ./bin/codex-maintainer self-audit --out "$tmp_dir/audit" >/dev/null

test -f "$tmp_dir/audit/self-audit.md"
test -f "$tmp_dir/audit/self-audit.json"
grep -q '"status": "pass"' "$tmp_dir/audit/self-audit.json"
grep -q '"commands_checked": 49' "$tmp_dir/audit/self-audit.json"
grep -q '"artifacts_checked": 144' "$tmp_dir/audit/self-audit.json"
grep -q '| codex-maintainer ci-gate --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer arena import --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer arena compare --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer arena sign --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer arena verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ci-summary --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer check-run --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer check-run post --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer sarif --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer docs-check --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios doctor --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios inventory --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios preview --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios devspace --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios target-match --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios codex-handoff --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios plan --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios prove --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios modernize --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios app-intelligence --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios ai-readiness --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios redact --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios threat-model --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios eval --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios demo --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer ios goals --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer transcript redact --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer transcript verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer transcript corpus --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer release-attest build --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer release-proof build --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer release-index build --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer release-manifest --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer release-manifest verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer release-replay verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer release-consume verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer release-diff compare --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer release-evidence site --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer release-evidence index --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer release-evidence bundle --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer release-evidence verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer release-evidence negative-index --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| codex-maintainer next-goal --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/demo-reports/leaderboard.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/demo-reports/transcripts/corpus.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/demo-reports/transcripts/index.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/arena-compare/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/docs-check/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-consume/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-diff/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-evidence/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-evidence-negative-index/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-evidence-verify/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-proof/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/transcript-corpus/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/transcript-verify/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/next-goal.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/arena-compare-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/sarif.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/docs-check-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/docs-check.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/core-loop.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/ios-shipguard.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/ios-preview.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/shipguard-devspace.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/oss-evaluation.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/superpowers/specs/2026-06-16-ios-preview-bridge-design.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/superpowers/specs/2026-06-16-shipguard-devspace-mcp-design.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/superpowers/plans/2026-06-16-oss-eval-improvements.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/superpowers/plans/2026-06-16-ios-shipguard-autonomous-loop.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/superpowers/plans/2026-06-16-ios-preview-bridge.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/superpowers/plans/2026-06-16-shipguard-devspace-mcp.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/ci-summary.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/check-run.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/template-profiles.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/transcript-corpus-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/transcript-corpus.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/transcript-redaction.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/transcript-verify-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-attest.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-consume-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-consume.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-diff-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-diff.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-bundle.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-index.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-negative-index-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-site.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-verify.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-proof.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-proof-consumption.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-manifest.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-index.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-proof-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-proof-workflows.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-replay.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-proof-on-tag.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/arena-compare.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/docs-check.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/transcript-corpus.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/transcript-verify.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-proof-manual.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-consume-verify.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-diff-compare.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-evidence-bundle.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-evidence-consume.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-evidence-export.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-evidence-negative-index.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/release-proof-consumption-checklist.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/redacted-transcript.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/transcripts/ios-notification-triage/transcript.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/transcripts/release-evidence-consumption/transcript.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/demo-ios-repo/DemoCodexMaintainerApp.xcodeproj/project.pbxproj | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/demo-ios-repo/DemoCodexMaintainerApp.xcodeproj/xcshareddata/xcschemes/DemoCodexMaintainerApp.xcscheme | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/demo-ios-repo/DemoCodexMaintainerApp.xcworkspace/contents.xcworkspacedata | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/demo-ios-repo/DemoCodexMaintainerApp.xctestplan | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/demo-ios-repo/DemoProducts.storekit | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/demo-ios-repo/PrivacyInfo.xcprivacy | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/demo-ios-repo/Sources/DemoCodexMaintainerApp/DemoCodexMaintainerApp.entitlements | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/demo-ios-repo/Sources/DemoCodexMaintainerApp/DemoPermissions.swift | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/demo-ios-repo/Sources/DemoCodexMaintainerApp/Info.plist | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/demo-ios-repo/Tests/DemoCodexMaintainerAppTests/DemoPermissionsTests.swift | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| templates/web/AGENTS.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| templates/backend/AGENTS.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| templates/cli/AGENTS.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/external-arena-pack/imported-clean/run.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/release-evidence/negative/README.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/release-evidence/negative/cases.tsv | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/arena_sign.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/arena_compare.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/arena_verify.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_attest.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_consume.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_diff.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_evidence.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_proof.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_index.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_manifest.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_replay.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_doctor.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_goal_loop.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_inventory.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_preview.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_codex_handoff.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_plan.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_prove.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_target_match.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_modernize.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_app_intelligence.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_ai_readiness.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_redaction.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_threat_model.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_shipguard_demo.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/ios_shipguard_eval.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/shipguard_devspace_mcp.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/lib/safe_paths.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/transcript_redact.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/transcript_verify.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/transcript_corpus.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| evals/README.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| evals/cases.jsonl | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| evals/ios_shipguard_cases.jsonl | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| evals/run_local.py | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| .agents/plugins/marketplace.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/ios_codex_handoff_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/ios_plan_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/ios_prove_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/ios_target_match_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/ios_modernize_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/ios_app_intelligence_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/ios_ai_readiness_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/ios_redaction_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/ios_threat_model_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/ios_shipguard_demo_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/ios_shipguard_eval_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| tests/shipguard_devspace_mcp_test.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| plugins/ios-shipguard/.mcp.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| plugins/ios-shipguard/.codex-plugin/plugin.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| plugins/ios-shipguard/skills/ios-shipguard/SKILL.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| plugins/ios-shipguard/skills/ios-shipguard/agents/openai.yaml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| plugins/ios-shipguard/skills/ios-shipguard/references/modes.md | pass |' "$tmp_dir/audit/self-audit.md"

echo "self audit tests passed"
