#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

cd "$repo_root"

./bin/shipguard self-audit --help >/dev/null
SHIPGUARD_GENERATED_AT="2026-06-16T00:00:00Z" \
  ./bin/shipguard self-audit --out "$tmp_dir/audit" >/dev/null

test -f "$tmp_dir/audit/self-audit.md"
test -f "$tmp_dir/audit/self-audit.json"
grep -q '"status": "pass"' "$tmp_dir/audit/self-audit.json"
grep -q '"commands_checked": 33' "$tmp_dir/audit/self-audit.json"
grep -q '"artifacts_checked": 81' "$tmp_dir/audit/self-audit.json"
grep -q '| shipguard ci-gate --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard arena import --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard arena compare --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard arena sign --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard arena verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard ci-summary --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard check-run --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard check-run post --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard sarif --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard docs-check --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard transcript redact --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard transcript verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard transcript corpus --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-attest build --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-proof build --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-index build --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-manifest --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-manifest verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-replay verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-consume verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-diff compare --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-evidence site --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-evidence index --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-evidence bundle --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-evidence verify --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard release-evidence negative-index --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| shipguard next-goal --help | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/demo-reports/leaderboard.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/demo-reports/transcripts/corpus.json | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/demo-reports/transcripts/index.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/arena-compare/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-consume/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-diff/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-evidence/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-evidence-negative-index/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-evidence-verify/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/release-proof/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/transcript-corpus/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| actions/transcript-verify/action.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/next-goal.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/arena-compare-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/sarif.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/docs-check.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/ci-summary.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/check-run.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/template-profiles.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/transcript-corpus-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/transcript-corpus.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/transcript-redaction.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/transcript-verify-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-attest.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-consume-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-consume.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-diff-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-diff.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-bundle.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-index.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-negative-index-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-site.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-evidence-verify.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-proof.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-proof-consumption.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-manifest.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-index.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-proof-action.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-proof-workflows.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| docs/release-replay.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-proof-on-tag.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/arena-compare.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/transcript-corpus.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/transcript-verify.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-proof-manual.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-consume-verify.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-diff-compare.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-evidence-bundle.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-evidence-consume.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-evidence-export.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/workflows/release-evidence-negative-index.yml | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/release-proof-consumption-checklist.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| examples/redacted-transcript.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/transcripts/ios-notification-triage/transcript.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/transcripts/release-evidence-consumption/transcript.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| templates/web/AGENTS.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| templates/backend/AGENTS.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| templates/cli/AGENTS.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/external-arena-pack/imported-clean/run.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/release-evidence/negative/README.md | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| fixtures/release-evidence/negative/cases.tsv | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/arena_sign.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/arena_compare.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/arena_verify.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_attest.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_consume.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_diff.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_evidence.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_proof.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_index.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_manifest.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/release_replay.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/transcript_redact.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/transcript_verify.sh | pass |' "$tmp_dir/audit/self-audit.md"
grep -q '| scripts/transcript_corpus.sh | pass |' "$tmp_dir/audit/self-audit.md"

echo "self audit tests passed"
