#!/usr/bin/env bash

set -euo pipefail

tool_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<'USAGE'
shipguard release-proof

Usage:
  shipguard release-proof build --out <dir> --release-url <url> [--version <version>] [--tag <tag>] [--commit <sha>] [--ci-run-url <url>] [--issue-url <url>] [--notes <text>]

Outputs:
  shipguard-vX.Y.Z.tar.gz
  proof/release-manifest.json
  proof/proof-ledger.md
  index/release-index.json
  index/release-index.md
  replay/replay-report.json
  replay/replay-report.md
  attestation/attestation.json
  attestation/attestation.md
  attestation/attestation-badge.json
USAGE
}

fail() {
  echo "release-proof: $*" >&2
  exit 1
}

cmd_build() {
  local out_dir=""
  local version=""
  local tag=""
  local commit=""
  local ci_run_url=""
  local release_url=""
  local issue_url=""
  local notes="Generated by shipguard release-proof build."

  while [[ "$#" -gt 0 ]]; do
    case "$1" in
      --out)
        [[ "$#" -ge 2 && -n "${2:-}" ]] || fail "--out requires a value"
        out_dir="$2"
        shift 2
        ;;
      --version)
        [[ "$#" -ge 2 && -n "${2:-}" ]] || fail "--version requires a value"
        version="$2"
        shift 2
        ;;
      --tag)
        [[ "$#" -ge 2 && -n "${2:-}" ]] || fail "--tag requires a value"
        tag="$2"
        shift 2
        ;;
      --commit)
        [[ "$#" -ge 2 && -n "${2:-}" ]] || fail "--commit requires a value"
        commit="$2"
        shift 2
        ;;
      --ci-run-url)
        [[ "$#" -ge 2 && -n "${2:-}" ]] || fail "--ci-run-url requires a value"
        ci_run_url="$2"
        shift 2
        ;;
      --release-url)
        [[ "$#" -ge 2 && -n "${2:-}" ]] || fail "--release-url requires a value"
        release_url="$2"
        shift 2
        ;;
      --issue-url)
        [[ "$#" -ge 2 && -n "${2:-}" ]] || fail "--issue-url requires a value"
        issue_url="$2"
        shift 2
        ;;
      --notes)
        [[ "$#" -ge 2 && -n "${2:-}" ]] || fail "--notes requires a value"
        notes="$2"
        shift 2
        ;;
      --help|-h)
        usage
        exit 0
        ;;
      *)
        fail "unknown build argument: $1"
        ;;
    esac
  done

  [[ -n "$out_dir" ]] || fail "--out is required"
  [[ -n "$release_url" ]] || fail "--release-url is required"
  [[ "$release_url" == https://github.com/*/releases/tag/v* ]] || fail "--release-url must be a GitHub release tag URL"

  [[ -n "$version" ]] || version="$(sed -n '1p' "$tool_root/VERSION")"
  [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "--version must be semantic"
  [[ -n "$tag" ]] || tag="v$version"
  [[ "$tag" == "v$version" ]] || fail "--tag must equal v$version"
  [[ "$release_url" == *"/releases/tag/$tag" ]] || fail "--release-url must end with /releases/tag/$tag"

  if [[ -z "$commit" ]] && git -C "$tool_root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    commit="$(git -C "$tool_root" rev-parse HEAD)"
  fi
  [[ -n "$commit" ]] || commit="unknown"

  mkdir -p "$out_dir"

  local packaged_tarball
  packaged_tarball="$("$tool_root/scripts/package_release.sh")"
  local release_tarball="$out_dir/$(basename "$packaged_tarball")"
  cp "$packaged_tarball" "$release_tarball"

  local proof_dir="$out_dir/proof"
  local index_dir="$out_dir/index"
  local replay_dir="$out_dir/replay"
  local attestation_dir="$out_dir/attestation"

  "$tool_root/bin/shipguard" release-manifest \
    --tarball "$release_tarball" \
    --out "$proof_dir" \
    --version "$version" \
    --tag "$tag" \
    --commit "$commit" \
    --ci-run-url "$ci_run_url" \
    --release-url "$release_url" \
    --issue-url "$issue_url" \
    --notes "$notes"

  "$tool_root/bin/shipguard" release-manifest verify \
    --manifest "$proof_dir/release-manifest.json" \
    --tarball "$release_tarball" \
    --version "$version" \
    --tag "$tag"

  "$tool_root/bin/shipguard" release-index build \
    --manifest "$proof_dir/release-manifest.json" \
    --out "$index_dir"

  "$tool_root/bin/shipguard" release-replay verify \
    --manifest "$proof_dir/release-manifest.json" \
    --tarball "$release_tarball" \
    --index "$index_dir/release-index.json" \
    --ledger "$proof_dir/proof-ledger.md" \
    --out "$replay_dir"

  "$tool_root/bin/shipguard" release-attest build \
    --manifest "$proof_dir/release-manifest.json" \
    --replay "$replay_dir/replay-report.json" \
    --out "$attestation_dir"

  echo "tarball: $release_tarball"
  echo "manifest: $proof_dir/release-manifest.json"
  echo "replay: $replay_dir/replay-report.json"
  echo "attestation: $attestation_dir/attestation.json"
  echo "attestation-badge: $attestation_dir/attestation-badge.json"
}

subcommand="${1:-}"
[[ "$subcommand" == "build" ]] || fail "release-proof requires subcommand: build"
shift || true
cmd_build "$@"
